# SPDX-FileCopyrightText: 2024 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [ "app",
    "client",
    "logic",
    "nanotime",
    "server",
]
resolver = "2"

[patch.crates-io]
quad-net = { path = "./quad-net" }
