# SPDX-FileCopyrightText: 2024 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "edrefis"
SPDX-PackageSupplier = "Janet Blackquill <uhhadd@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/pontaoski/edrefis"

[[annotations]]
path = "Cargo.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Janet Blackquill <uhhadd@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "app/src/audio/*.wav"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Damian Yerrick <https://pineight.com/contact/>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "client/src/audio/*.wav"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Damian Yerrick <https://pineight.com/contact/>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "app/src/font/HankenGrotesk-*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 The Hanken Grotesk Project Authors (https://github.com/marcologous/hanken-grotesk)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "client/src/font/HankenGrotesk-*"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 The Hanken Grotesk Project Authors (https://github.com/marcologous/hanken-grotesk)"
SPDX-License-Identifier = "OFL-1.1"
