# SPDX-FileCopyrightText: 2024 Janet Blackquill <uhhadd@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
logic = { path = "../logic" }
nanoserde = "0.1.37"
quad-net = "0.1.2"
